target_name : 'Target_2_sins'

simple_data_prep:
  samples: 100
  noise: 0.0
  # wind_size: 0
  # wind_step: 0
  # horizon: 0
  train_pc: 0.7
  seed: 1410

sw_data_prep:
  samples: 100
  noise: 0.0
  wind_size: 5
  wind_step: 1 
  horizon: 1
  train_pc: 0.7
  seed: 2024

# plots

simple_plot_tr_ts:
  xlim: [-6.7 , 6.7]
  ylim: [0.05, 1]
  colors: ['lightblue', 'blue', 'red', 'blue', 'red']
  linestyles: ['dashed', 'solid', 'solid']
  title: 'Dataset for curve fitting ("2_sins" data, with 100 samples)'

sw_plot_tr_ts:
  ylim: [0.05, 1]
  colors: ['lightblue', 'blue', 'red']
  marker_colors: [None, 'white', 'white', 'lightblue', 'mistyrose']
  xlabel: 'Range (overlapping windows)'
  ylabel: 'Target value (averaged)'
  labels: ['Target function', 'Training', 'Validation']
  linestyles: ['dashed', 'solid', 'solid']
  lines: ['dashed', 'solid', 'solid']
  markers: [None, 'o', 'o']
  legend_cols: 3
  title: 'Dataset for TS forecasting ("2_sins" data, with 100 samples)'
